=== JoanneZamorano/LM_clases/clase 09_22/03_DTDexterno/ejercicio1.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo, autor+, anio, genero)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT genero (#PCDATA)>

=== JoanneZamorano/LM_clases/clase 09_22/03_DTDexterno/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "ejercicio1.dtd">
<biblioteca>
    <libro>
        <titulo></titulo>
        <autor></autor>
        <anio></anio>
        <genero></genero>
    </libro>
    <libro>
        <titulo></titulo>
        <autor></autor>
        <anio></anio>
        <genero></genero>
    </libro>
</biblioteca>
